version: 2

before:
  hooks:
    - git submodule update --init --recursive

builds:
  - id: proxmox-tui
    main: ./cmd/proxmox-tui
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64, 386]
    ignore:
      - goos: windows
        goarch: amd64
    ldflags:
      - -s -w
      - -X github.com/devnullvoid/proxmox-tui/internal/version.version={{.Version}}
      - -X github.com/devnullvoid/proxmox-tui/internal/version.commit={{.Commit}}
      - -X github.com/devnullvoid/proxmox-tui/internal/version.buildDate={{.Date}}

  - id: proxmox-tui-windows-amd64
    main: ./cmd/proxmox-tui
    env:
      - CGO_ENABLED=0
    goos: [windows]
    goarch: [amd64]
    goamd64: [v1]
    tags: [netgo, osusergo]
    ldflags:
      - -s -w
      - -X github.com/devnullvoid/proxmox-tui/internal/version.version={{.Version}}
      - -X github.com/devnullvoid/proxmox-tui/internal/version.commit={{.Commit}}
      - -X github.com/devnullvoid/proxmox-tui/internal/version.buildDate={{.Date}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums_{{ .Version }}.txt"

changelog:
  use: git
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  draft: false
  prerelease: auto

# AUR Package (Binary)
aurs:
  - name: proxmox-tui-bin
    homepage: "https://github.com/devnullvoid/proxmox-tui"
    description: "A terminal user interface (TUI) for Proxmox VE"
    maintainers:
      - "devnullvoid <devnullvoid.space@gmail.com>"
    license: "MIT"
    conflicts:
      - "proxmox-tui"
      - "proxmox-tui-git"
    provides:
      - "proxmox-tui"
    depends:
      - "glibc"
    optdepends:
      - "kitty: Better terminal support"
      - "alacritty: Better terminal support"
    package: |-
      # Install binary
      install -Dm755 "./proxmox-tui" "${pkgdir}/usr/bin/proxmox-tui"

      # Install license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/proxmox-tui/LICENSE"

      # Install documentation
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/proxmox-tui/README.md"

# AUR Package (Source)
aur_sources:
  - name: proxmox-tui
    homepage: "https://github.com/devnullvoid/proxmox-tui"
    description: "A terminal user interface (TUI) for Proxmox VE"
    maintainers:
      - "devnullvoid <devnullvoid.space@gmail.com>"
    license: "MIT"
    conflicts:
      - "proxmox-tui-bin"
      - "proxmox-tui-git"
    provides:
      - "proxmox-tui"
    depends:
      - "go"
      - "git"
    makedepends:
      - "make"
    optdepends:
      - "kitty: Better terminal support"
      - "alacritty: Better terminal support"
    url_template: "https://github.com/devnullvoid/proxmox-tui/archive/{{ .Tag }}.tar.gz"
    prepare: |-
      cd "${pkgname}-${pkgver}"
      go mod download
    build: |-
      cd "${pkgname}-${pkgver}"
      export CGO_CPPFLAGS="${CPPFLAGS}"
      export CGO_CFLAGS="${CFLAGS}"
      export CGO_CXXFLAGS="${CXXFLAGS}"
      export CGO_LDFLAGS="${LDFLAGS}"
      export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
      go build -ldflags="-w -s -buildid='' -linkmode=external -X github.com/devnullvoid/proxmox-tui/internal/version.version=${pkgver}" ./cmd/proxmox-tui
    package: |-
      cd "${pkgname}-${pkgver}"
      install -Dm755 ./proxmox-tui "${pkgdir}/usr/bin/proxmox-tui"
      install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/proxmox-tui/LICENSE"
      install -Dm644 README.md "${pkgdir}/usr/share/doc/proxmox-tui/README.md"

# Homebrew Casks
homebrew_casks:
  - name: proxmox-tui
    description: "A terminal user interface (TUI) for Proxmox VE"
    homepage: "https://github.com/devnullvoid/proxmox-tui"
    license: "MIT"
    binary: "proxmox-tui"
    repository:
      owner: "devnullvoid"
      name: "homebrew-proxmox-tui"
    commit_author:
      name: "GoReleaser Bot"
      email: "noreply@github.com"
    caveats: |
      proxmox-tui requires a Proxmox VE server to connect to.
      Run 'proxmox-tui --help' to see configuration options.
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/proxmox-tui"]
          end

# Scoop Manifest
scoops:
  - name: proxmox-tui
    description: "A terminal user interface (TUI) for Proxmox VE"
    homepage: "https://github.com/devnullvoid/proxmox-tui"
    license: "MIT"
    repository:
      owner: "devnullvoid"
      name: "scoop-proxmox-tui"
    commit_author:
      name: "GoReleaser Bot"
      email: "noreply@github.com"

# DEB Package
nfpms:
  - id: proxmox-tui-deb
    description: "A terminal user interface (TUI) for Proxmox VE"
    homepage: "https://github.com/devnullvoid/proxmox-tui"
    maintainer: "devnullvoid <devnullvoid.space@gmail.com>"
    license: "MIT"
    formats:
      - deb
    contents:
      - src: "{{ .ArtifactPath }}"
        dst: "/usr/local/bin/proxmox-tui"
        type: "file"
      - src: "LICENSE"
        dst: "/usr/share/doc/proxmox-tui/LICENSE"
        type: "doc"
      - src: "README.md"
        dst: "/usr/share/doc/proxmox-tui/README.md"
        type: "doc"
    overrides:
      deb:
        dependencies:
          - "libc6"
        recommends:
          - "kitty | alacritty"
        suggests:
          - "proxmox-ve"

  # RPM Package
  - id: proxmox-tui-rpm
    description: "A terminal user interface (TUI) for Proxmox VE"
    homepage: "https://github.com/devnullvoid/proxmox-tui"
    maintainer: "devnullvoid <devnullvoid.space@gmail.com>"
    license: "MIT"
    formats:
      - rpm
    contents:
      - src: "{{ .ArtifactPath }}"
        dst: "/usr/local/bin/proxmox-tui"
        type: "file"
      - src: "LICENSE"
        dst: "/usr/share/doc/proxmox-tui/LICENSE"
        type: "doc"
      - src: "README.md"
        dst: "/usr/share/doc/proxmox-tui/README.md"
        type: "doc"
    overrides:
      rpm:
        dependencies:
          - "glibc"
        suggests:
          - "kitty"
          - "alacritty"
          - "proxmox-ve"

# Docker Images
dockers:
  - image_templates:
      - "ghcr.io/devnullvoid/proxmox-tui:{{ .Version }}"
      - "ghcr.io/devnullvoid/proxmox-tui:latest"
    dockerfile: "Dockerfile"
    use: "buildx"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--platform=linux/arm64"
    extra_files:
      - LICENSE
      - README.md
