version: 2

before:
  hooks:
    - git submodule update --init --recursive

builds:
  # General build for all platforms except windows/amd64
  - id: peevetui
    main: ./cmd/peevetui
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: amd64
    ldflags:
      - -s -w
      - -X github.com/devnullvoid/peevetui/internal/version.version={{.Version}}
      - -X github.com/devnullvoid/peevetui/internal/version.commit={{.Commit}}
      - -X github.com/devnullvoid/peevetui/internal/version.buildDate={{.Date}}

  # Windows/amd64 build with extra compatibility settings
  - id: peevetui-windows-amd64
    main: ./cmd/peevetui
    env:
      - CGO_ENABLED=0
    goos: [windows]
    goarch: [amd64]
    goamd64: [v1]
    tags: [netgo, osusergo]
    ldflags:
      - -s -w
      - -X github.com/devnullvoid/peevetui/internal/version.version={{.Version}}
      - -X github.com/devnullvoid/peevetui/internal/version.commit={{.Commit}}
      - -X github.com/devnullvoid/peevetui/internal/version.buildDate={{.Date}}

archives:
  - id: default
    builds: [peevetui, peevetui-windows-amd64]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums_{{ .Version }}.txt"

changelog:
  use: git
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  draft: true
  prerelease: auto
