services:
  peevetui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    image: peevetui:latest
    container_name: peevetui
    restart: "no"  # Don't restart for interactive TUI apps

    # Environment variables are loaded from the .env file
    environment:
      - PROXMOX_ADDR=${PROXMOX_ADDR}
      - PROXMOX_USER=${PROXMOX_USER}
      - PROXMOX_PASSWORD=${PROXMOX_PASSWORD}
      - PROXMOX_REALM=${PROXMOX_REALM}
      - PROXMOX_TOKEN_ID=${PROXMOX_TOKEN_ID}
      - PROXMOX_TOKEN_SECRET=${PROXMOX_TOKEN_SECRET}
      - PROXMOX_API_PATH=${PROXMOX_API_PATH:-/api2/json}
      - PROXMOX_INSECURE=${PROXMOX_INSECURE:-false}
      - PROXMOX_DEBUG=${PROXMOX_DEBUG:-false}
      - PROXMOX_CACHE_DIR=${PROXMOX_CACHE_DIR:-/app/cache}
      - PROXMOX_SSH_USER=${PROXMOX_SSH_USER}

    # Volumes for persistence
    volumes:
      - ./cache:/app/cache

    # TTY and interactive for TUI applications
    tty: true
    stdin_open: true

    # Security options
    security_opt:
      - no-new-privileges:true

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'

# Note: For TUI applications, use 'docker-compose run' (not 'docker-compose up')
