services:
  pvetui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    image: pvetui:latest
    container_name: pvetui
    restart: "no"  # Don't restart for interactive TUI apps

    # Environment variables are loaded from the .env file
    environment:
      - PVETUI_ADDR=${PVETUI_ADDR}
      - PVETUI_USER=${PVETUI_USER}
      - PVETUI_PASSWORD=${PVETUI_PASSWORD}
      - PVETUI_REALM=${PVETUI_REALM}
      - PVETUI_TOKEN_ID=${PVETUI_TOKEN_ID}
      - PVETUI_TOKEN_SECRET=${PVETUI_TOKEN_SECRET}
      - PVETUI_API_PATH=${PVETUI_API_PATH:-/api2/json}
      - PVETUI_INSECURE=${PVETUI_INSECURE:-false}
      - PVETUI_DEBUG=${PVETUI_DEBUG:-false}
      - PVETUI_CACHE_DIR=${PVETUI_CACHE_DIR:-/app/cache}
      - PVETUI_SSH_USER=${PVETUI_SSH_USER}

    # Volumes for persistence
    volumes:
      - ./cache:/app/cache

    # TTY and interactive for TUI applications
    tty: true
    stdin_open: true

    # Security options
    security_opt:
      - no-new-privileges:true

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'

# Note: For TUI applications, use 'docker-compose run' (not 'docker-compose up')
