version: '3.8'

services:
  proxmox-tui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    image: proxmox-tui:latest
    container_name: proxmox-tui
    restart: "no"  # Don't restart for interactive TUI apps

    # Pass command-line flags to the entrypoint
    command: ["--config", "/app/config.yml"]

    # Remove environment variables for connection, use config file instead
    environment:
      - PROXMOX_DEBUG=${PROXMOX_DEBUG:-false}
      - PROXMOX_CACHE_DIR=${PROXMOX_CACHE_DIR:-/app/cache}

    # Volumes for persistence
    # Mount the root config.yml and the cache directory
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ./cache:/app/cache

    # TTY and interactive for TUI applications
    tty: true
    stdin_open: true

    # Security options
    security_opt:
      - no-new-privileges:true

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'

# Note: For TUI applications, use 'docker-compose up' (not 'docker-compose up -d')
# The -d flag runs in detached mode which doesn't work for interactive applications

# Optional: Redis for distributed caching (if needed in the future)
# redis:
#   image: redis:7-alpine
#   container_name: proxmox-tui-redis
#   restart: unless-stopped
#   volumes:
#     - redis_data:/data
#   command: redis-server --appendonly yes

# volumes:
#   redis_data:
