# Example multi-profile config for proxmox-tui
profiles:
  default:
    addr: https://proxmox.local:8006
    api_path: /api2/json
    user: root
    # password: "1234567890"
    token_id: "tui"
    token_secret: "1234567890"
    realm: pam
    insecure: true
    ssh_user: root
  work:
    addr: https://work-proxmox:8006
    api_path: /api2/json
    user: workuser
    token_id: worktoken
    token_secret: worksecret
    realm: pam
    insecure: false
    ssh_user: workuser
default_profile: default

debug: false
# cache_dir: "/custom/cache/path"  # Optional: overrides platform defaults

key_bindings:
  switch_view: "]"
  switch_view_reverse: "["
  nodes_page: "Alt+1"
  guests_page: "Alt+2"
  tasks_page: "Alt+3"
  menu: m
  shell: s
  vnc: v
  refresh: "Ctrl+r"
  auto_refresh: a
  search: "/"
  help: "?"
  quit: q
# Reserved keys (h, j, k, l, arrows, Tab, Enter, Esc, Backspace) cannot be reassigned.
# System combos like Ctrl+C, Ctrl+D and Ctrl+Z are also blocked.

# Theme configuration
theme:
  # Optionally set a built-in theme by name (e.g., "catppuccin-mocha").
  name: "default"
  # You can override any color from the built-in theme below.
  # colors:
    # primary: "white"
    # secondary: "gray"
    # tertiary: "aqua"
    # success: "green"
    # warning: "yellow"
    # error: "red"
    # info: "blue"
    # background: "default"
    # border: "gray"
    # selection: "blue"
    # header: "navy"
    # headertext: "yellow"
    # footer: "default"
    # footertext: "white"
    # title: "white"
    # contrast: "blue"
    # morecontrast: "fuchsia"
    # inverse: "black"
    # statusrunning: "green"
    # statusstopped: "maroon"
    # statuspending: "yellow"
    # statuserror: "red"
    # usagelow: "green"
    # usagemedium: "yellow"
    # usagehigh: "red"
    # usagecritical: "fuchsia"
