addr: https://proxmox.local:8006
api_path: /api2/json
user: root
# password: "1234567890"
token_id: "tui"
token_secret: "1234567890"
realm: pam
insecure: true
ssh_user: root
debug: false
# cache_dir: "/custom/cache/path"  # Optional: defaults to $XDG_CACHE_HOME/proxmox-tui or ~/.cache/proxmox-tui

key_bindings:
  switch_view: "]"
  switch_view_reverse: "["
  nodes_page: "Alt+1"
  guests_page: "Alt+2"
  tasks_page: "Alt+3"
  menu: m
  shell: s
  vnc: v
  scripts: c
  refresh: "Ctrl+r"
  auto_refresh: a
  search: "/"
  help: "?"
  quit: q
# Reserved keys (h, j, k, l, arrows, Tab, Enter, Esc, Backspace) cannot be reassigned.
# System combos like Ctrl+C, Ctrl+D and Ctrl+Z are also blocked.

# Theme configuration
theme:
  # Enable terminal emulator color scheme adaptation (recommended)
  use_terminal_colors: true
  # Color scheme: "default", "light", "dark"
  color_scheme: default
  colors:
    primary: "white"
    secondary: "gray"
    tertiary: "aqua"
    success: "green"
    warning: "yellow"
    error: "red"
    info: "blue"
    background: "default"
    border: "gray"
    selection: "blue"
    header: "navy"
    headertext: "yellow"
    footer: "default"
    footertext: "white"
    title: "white"
    contrast: "blue"
    morecontrast: "fuchsia"
    inverse: "black"
    statusrunning: "green"
    statusstopped: "maroon"
    statuspending: "yellow"
    statuserror: "red"
    usagelow: "green"
    usagemedium: "yellow"
    usagehigh: "red"
    usagecritical: "fuchsia"
