name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.24.2]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -o proxmox-tui ./cmd/proxmox-tui

    - name: Verify build
      run: |
        ls -la proxmox-tui
        ./proxmox-tui --help || echo "Binary built successfully (help may require config)"

    - name: Test
      run: go test -v ./... 