name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Generate release notes from CHANGELOG.md
        id: notes
        run: |
          set -euo pipefail
          ver="${GITHUB_REF_NAME#v}"
          tag="${GITHUB_REF_NAME}"
          tmp=/tmp/RELEASE_NOTES.md
          section=$(sed -n "/^## \\[${ver}\\]/,/^## \\[/p" CHANGELOG.md || true)
          body=$(printf "%s\n" "$section" | sed '/^## \[/d' | tail -n +2)
          if [ -z "${body}" ]; then
            echo "No changelog section found for ${ver} in CHANGELOG.md" >&2
            exit 1
          fi
          {
            printf "## 🚀 Release %s\n\n" "$tag"
            printf "%s\n" "$body"
          } > "$tmp"
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --release-notes /tmp/RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
