name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build binaries
      run: |
        mkdir -p dist
        
        # Linux AMD64
        GOOS=linux GOARCH=amd64 go build -o dist/proxmox-tui-linux-amd64 ./cmd/proxmox-tui
        
        # Linux ARM64
        GOOS=linux GOARCH=arm64 go build -o dist/proxmox-tui-linux-arm64 ./cmd/proxmox-tui
        
        # macOS AMD64
        GOOS=darwin GOARCH=amd64 go build -o dist/proxmox-tui-darwin-amd64 ./cmd/proxmox-tui
        
        # macOS ARM64
        GOOS=darwin GOARCH=arm64 go build -o dist/proxmox-tui-darwin-arm64 ./cmd/proxmox-tui
        
        # Windows AMD64
        GOOS=windows GOARCH=amd64 go build -o dist/proxmox-tui-windows-amd64.exe ./cmd/proxmox-tui
        
        # Verify builds
        ls -la dist/

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
        generate_release_notes: true 